# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "15f0a10bc86df9d36a02da61ce944525"
name = "Gwl Donation review "
application_url = "https://smart-donation-enhancement.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create", "orders/paid" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/subscription_contracts/create"
  topics = [ "subscription_contracts/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/subscription_billing_attempts/success"
  topics = [ "subscription_billing_attempts/success" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/subscription_billing_attempts/failure"
  topics = [ "subscription_billing_attempts/failure" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/cancelled"
  topics = [ "orders/cancelled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/refunds/create"
  topics = [ "refunds/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/subscription_contracts/update"
  topics = [ "subscription_contracts/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app_subscriptions/update"
  topics = [ "app_subscriptions/update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_payment_methods,read_customers,read_orders,read_own_subscription_contracts,read_publications,read_purchase_options,write_customers,write_orders,write_own_subscription_contracts,write_products,write_publications,write_purchase_options"

[auth]
redirect_urls = [
  "https://smart-donation-enhancement.vercel.app/auth/callback",
  "https://smart-donation-enhancement.vercel.app/api/auth"
]

[app_proxy]
url = "https://smart-donation-enhancement.vercel.app"
subpath = "smart-donate-enhancement"
prefix = "apps"
