api_version = "2026-04"


[[extensions]]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
handle = "purchase-options-action"
type = "ui_extension"
uid = "1a95d495-8a27-0f4b-4a55-6d4a5621f8eb64048896"

# Both targets need to be specified for the extensions to work
[[extensions.targeting]]
module = "./src/ProductExtension.jsx"
target = "admin.product-purchase-option.action.render"

[[extensions.targeting]]
module = "./src/ProductVariantExtension.jsx"
target = "admin.product-variant-purchase-option.action.render"

# Valid extension targets:

# Product index and detail pages
# - admin.product-purchase-option.action.render

# Product variant detail pages
# - admin.product-variant-purchase-option.action.render

[extensions.capabilities]
api_access = true
network_access = true
