// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/subscription_billing_attempts/failure": {
    params: {};
  };
  "/webhooks/subscription_billing_attempts/success": {
    params: {};
  };
  "/webhooks/subscription_contracts/create": {
    params: {};
  };
  "/webhooks/subscription_contracts/update": {
    params: {};
  };
  "/webhooks/app_subscriptions/update": {
    params: {};
  };
  "/api/customer/subscription-action": {
    params: {};
  };
  "/api/customer/subscription-status": {
    params: {};
  };
  "/webhooks/customers/data_request": {
    params: {};
  };
  "/api/customer/receipt-download": {
    params: {};
  };
  "/apps/portion-sale/settings": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/api/cron/payment-recovery": {
    params: {};
  };
  "/api/resend-donation-email": {
    params: {};
  };
  "/webhooks/customers/redact": {
    params: {};
  };
  "/webhooks/orders/cancelled": {
    params: {};
  };
  "/api/custom-donation-cart": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/refunds/create": {
    params: {};
  };
  "/webhooks/orders/create": {
    params: {};
  };
  "/api/download-receipt": {
    params: {};
  };
  "/webhooks/shop/redact": {
    params: {};
  };
  "/api/preview-receipt": {
    params: {};
  };
  "/api/cron/reminders": {
    params: {};
  };
  "/api/selling-plans": {
    params: {};
  };
  "/api/block-config": {
    params: {};
  };
  "/api/cron/billing": {
    params: {};
  };
  "/api/portion-sale": {
    params: {};
  };
  "/api/portion-sale/settings": {
    params: {};
  };
  "/api/plan-status": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
  "/api/campaigns": {
    params: {};
  };
  "/documentation": {
    params: {};
  };
  "/subscriptions": {
    params: {};
  };
  "/subscriptions/:id": {
    params: {
      "id": string;
    };
  };
  "/auth/login": {
    params: {};
  };
  "/receipts": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/recurring-subscriptions/edit": {
    params: {};
  };
  "/app/preset-donation/delete/:id": {
    params: {
      "id": string;
    };
  };
  "/app/preset-donation/edit/:id": {
    params: {
      "id": string;
    };
  };
  "/app/recurring-subscriptions": {
    params: {};
  };
  "/app/preset-donation/add": {
    params: {};
  };
  "/app/subscription-detail": {
    params: {};
  };
  "/app/donation-activity": {
    params: {};
  };
  "/app/billing-attempts": {
    params: {};
  };
  "/app/payment-recovery": {
    params: {};
  };
  "/app/perset-donation": {
    params: {};
  };
  "/app/preset-donation": {
    params: {};
  };
  "/app/email-settings": {
    params: {};
  };
  "/app/track-donation": {
    params: {};
  };
  "/app/portion-sale": {
    params: {};
  };
  "/app/diagnostics": {
    params: {};
  };
  "/app/billing": {
    params: {};
  };
  "/app/pricing": {
    params: {};
  };
  "/app/roundup": {
    params: {};
  };
  "/app/help": {
    params: {};
  };
  "/faq": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/subscription_billing_attempts/failure" | "/webhooks/subscription_billing_attempts/success" | "/webhooks/subscription_contracts/create" | "/webhooks/subscription_contracts/update" | "/webhooks/app_subscriptions/update" | "/api/customer/subscription-action" | "/api/customer/subscription-status" | "/webhooks/customers/data_request" | "/api/customer/receipt-download" | "/apps/portion-sale/settings" | "/webhooks/app/scopes_update" | "/api/cron/payment-recovery" | "/api/resend-donation-email" | "/webhooks/customers/redact" | "/webhooks/orders/cancelled" | "/api/custom-donation-cart" | "/webhooks/app/uninstalled" | "/webhooks/refunds/create" | "/webhooks/orders/create" | "/api/download-receipt" | "/webhooks/shop/redact" | "/api/preview-receipt" | "/api/cron/reminders" | "/api/selling-plans" | "/api/block-config" | "/api/cron/billing" | "/api/portion-sale" | "/api/portion-sale/settings" | "/api/plan-status" | "/privacy-policy" | "/api/campaigns" | "/documentation" | "/subscriptions" | "/subscriptions/:id" | "/auth/login" | "/receipts" | "/auth/*" | "/app" | "/app/recurring-subscriptions/edit" | "/app/preset-donation/delete/:id" | "/app/preset-donation/edit/:id" | "/app/recurring-subscriptions" | "/app/preset-donation/add" | "/app/subscription-detail" | "/app/donation-activity" | "/app/billing-attempts" | "/app/payment-recovery" | "/app/perset-donation" | "/app/preset-donation" | "/app/email-settings" | "/app/track-donation" | "/app/portion-sale" | "/app/diagnostics" | "/app/billing" | "/app/pricing" | "/app/roundup" | "/app/help" | "/faq";
  };
  "routes/webhooks.subscription_billing_attempts.failure.tsx": {
    id: "routes/webhooks.subscription_billing_attempts.failure";
    page: "/webhooks/subscription_billing_attempts/failure";
  };
  "routes/webhooks.subscription_billing_attempts.success.tsx": {
    id: "routes/webhooks.subscription_billing_attempts.success";
    page: "/webhooks/subscription_billing_attempts/success";
  };
  "routes/webhooks.subscription_contracts.create.tsx": {
    id: "routes/webhooks.subscription_contracts.create";
    page: "/webhooks/subscription_contracts/create";
  };
  "routes/webhooks.subscription_contracts.update.tsx": {
    id: "routes/webhooks.subscription_contracts.update";
    page: "/webhooks/subscription_contracts/update";
  };
  "routes/webhooks.app_subscriptions.update.tsx": {
    id: "routes/webhooks.app_subscriptions.update";
    page: "/webhooks/app_subscriptions/update";
  };
  "routes/api.customer.subscription-action.tsx": {
    id: "routes/api.customer.subscription-action";
    page: "/api/customer/subscription-action";
  };
  "routes/api.customer.subscription-status.tsx": {
    id: "routes/api.customer.subscription-status";
    page: "/api/customer/subscription-status";
  };
  "routes/webhooks.customers.data_request.tsx": {
    id: "routes/webhooks.customers.data_request";
    page: "/webhooks/customers/data_request";
  };
  "routes/api.customer.receipt-download.tsx": {
    id: "routes/api.customer.receipt-download";
    page: "/api/customer/receipt-download";
  };
  "routes/apps.portion-sale.settings.tsx": {
    id: "routes/apps.portion-sale.settings";
    page: "/apps/portion-sale/settings";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/api.cron.payment-recovery.tsx": {
    id: "routes/api.cron.payment-recovery";
    page: "/api/cron/payment-recovery";
  };
  "routes/api.resend-donation-email.tsx": {
    id: "routes/api.resend-donation-email";
    page: "/api/resend-donation-email";
  };
  "routes/webhooks.customers.redact.tsx": {
    id: "routes/webhooks.customers.redact";
    page: "/webhooks/customers/redact";
  };
  "routes/webhooks.orders.cancelled.tsx": {
    id: "routes/webhooks.orders.cancelled";
    page: "/webhooks/orders/cancelled";
  };
  "routes/api.custom-donation-cart.tsx": {
    id: "routes/api.custom-donation-cart";
    page: "/api/custom-donation-cart";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.refunds.create.tsx": {
    id: "routes/webhooks.refunds.create";
    page: "/webhooks/refunds/create";
  };
  "routes/webhooks.orders.create.tsx": {
    id: "routes/webhooks.orders.create";
    page: "/webhooks/orders/create";
  };
  "routes/api.download-receipt.tsx": {
    id: "routes/api.download-receipt";
    page: "/api/download-receipt";
  };
  "routes/webhooks.shop.redact.tsx": {
    id: "routes/webhooks.shop.redact";
    page: "/webhooks/shop/redact";
  };
  "routes/api.preview-receipt.tsx": {
    id: "routes/api.preview-receipt";
    page: "/api/preview-receipt";
  };
  "routes/api.cron.reminders.tsx": {
    id: "routes/api.cron.reminders";
    page: "/api/cron/reminders";
  };
  "routes/api.selling-plans.ts": {
    id: "routes/api.selling-plans";
    page: "/api/selling-plans";
  };
  "routes/api.block-config.tsx": {
    id: "routes/api.block-config";
    page: "/api/block-config";
  };
  "routes/api.cron.billing.tsx": {
    id: "routes/api.cron.billing";
    page: "/api/cron/billing";
  };
  "routes/api.portion-sale.tsx": {
    id: "routes/api.portion-sale";
    page: "/api/portion-sale" | "/api/portion-sale/settings";
  };
  "routes/api.portion-sale.settings.tsx": {
    id: "routes/api.portion-sale.settings";
    page: "/api/portion-sale/settings";
  };
  "routes/api.plan-status.tsx": {
    id: "routes/api.plan-status";
    page: "/api/plan-status";
  };
  "routes/privacy-policy.tsx": {
    id: "routes/privacy-policy";
    page: "/privacy-policy";
  };
  "routes/api.campaigns.tsx": {
    id: "routes/api.campaigns";
    page: "/api/campaigns";
  };
  "routes/documentation.tsx": {
    id: "routes/documentation";
    page: "/documentation";
  };
  "routes/subscriptions.tsx": {
    id: "routes/subscriptions";
    page: "/subscriptions" | "/subscriptions/:id";
  };
  "routes/subscriptions.$id.tsx": {
    id: "routes/subscriptions.$id";
    page: "/subscriptions/:id";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/receipts.tsx": {
    id: "routes/receipts";
    page: "/receipts";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/recurring-subscriptions/edit" | "/app/preset-donation/delete/:id" | "/app/preset-donation/edit/:id" | "/app/recurring-subscriptions" | "/app/preset-donation/add" | "/app/subscription-detail" | "/app/donation-activity" | "/app/billing-attempts" | "/app/payment-recovery" | "/app/perset-donation" | "/app/preset-donation" | "/app/email-settings" | "/app/track-donation" | "/app/portion-sale" | "/app/diagnostics" | "/app/billing" | "/app/pricing" | "/app/roundup" | "/app/help";
  };
  "routes/app.recurring-subscriptions_.edit.tsx": {
    id: "routes/app.recurring-subscriptions_.edit";
    page: "/app/recurring-subscriptions/edit";
  };
  "routes/app.preset-donation_.delete.$id.tsx": {
    id: "routes/app.preset-donation_.delete.$id";
    page: "/app/preset-donation/delete/:id";
  };
  "routes/app.preset-donation_.edit.$id.tsx": {
    id: "routes/app.preset-donation_.edit.$id";
    page: "/app/preset-donation/edit/:id";
  };
  "routes/app.recurring-subscriptions.tsx": {
    id: "routes/app.recurring-subscriptions";
    page: "/app/recurring-subscriptions";
  };
  "routes/app.preset-donation_.add.tsx": {
    id: "routes/app.preset-donation_.add";
    page: "/app/preset-donation/add";
  };
  "routes/app.subscription-detail.tsx": {
    id: "routes/app.subscription-detail";
    page: "/app/subscription-detail";
  };
  "routes/app.donation-activity.tsx": {
    id: "routes/app.donation-activity";
    page: "/app/donation-activity";
  };
  "routes/app.billing-attempts.tsx": {
    id: "routes/app.billing-attempts";
    page: "/app/billing-attempts";
  };
  "routes/app.payment-recovery.tsx": {
    id: "routes/app.payment-recovery";
    page: "/app/payment-recovery";
  };
  "routes/app.perset-donation.tsx": {
    id: "routes/app.perset-donation";
    page: "/app/perset-donation";
  };
  "routes/app.preset-donation.tsx": {
    id: "routes/app.preset-donation";
    page: "/app/preset-donation";
  };
  "routes/app.email-settings.tsx": {
    id: "routes/app.email-settings";
    page: "/app/email-settings";
  };
  "routes/app.track-donation.tsx": {
    id: "routes/app.track-donation";
    page: "/app/track-donation";
  };
  "routes/app.portion-sale.tsx": {
    id: "routes/app.portion-sale";
    page: "/app/portion-sale";
  };
  "routes/app.diagnostics.tsx": {
    id: "routes/app.diagnostics";
    page: "/app/diagnostics";
  };
  "routes/app.billing.tsx": {
    id: "routes/app.billing";
    page: "/app/billing";
  };
  "routes/app.pricing.tsx": {
    id: "routes/app.pricing";
    page: "/app/pricing";
  };
  "routes/app.roundup.tsx": {
    id: "routes/app.roundup";
    page: "/app/roundup";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.help.tsx": {
    id: "routes/app.help";
    page: "/app/help";
  };
  "routes/faq.tsx": {
    id: "routes/faq";
    page: "/faq";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.subscription_billing_attempts.failure": typeof import("./app/routes/webhooks.subscription_billing_attempts.failure.tsx");
  "routes/webhooks.subscription_billing_attempts.success": typeof import("./app/routes/webhooks.subscription_billing_attempts.success.tsx");
  "routes/webhooks.subscription_contracts.create": typeof import("./app/routes/webhooks.subscription_contracts.create.tsx");
  "routes/webhooks.subscription_contracts.update": typeof import("./app/routes/webhooks.subscription_contracts.update.tsx");
  "routes/webhooks.app_subscriptions.update": typeof import("./app/routes/webhooks.app_subscriptions.update.tsx");
  "routes/api.customer.subscription-action": typeof import("./app/routes/api.customer.subscription-action.tsx");
  "routes/api.customer.subscription-status": typeof import("./app/routes/api.customer.subscription-status.tsx");
  "routes/webhooks.customers.data_request": typeof import("./app/routes/webhooks.customers.data_request.tsx");
  "routes/api.customer.receipt-download": typeof import("./app/routes/api.customer.receipt-download.tsx");
  "routes/apps.portion-sale.settings": typeof import("./app/routes/apps.portion-sale.settings.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/api.cron.payment-recovery": typeof import("./app/routes/api.cron.payment-recovery.tsx");
  "routes/api.resend-donation-email": typeof import("./app/routes/api.resend-donation-email.tsx");
  "routes/webhooks.customers.redact": typeof import("./app/routes/webhooks.customers.redact.tsx");
  "routes/webhooks.orders.cancelled": typeof import("./app/routes/webhooks.orders.cancelled.tsx");
  "routes/api.custom-donation-cart": typeof import("./app/routes/api.custom-donation-cart.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/webhooks.refunds.create": typeof import("./app/routes/webhooks.refunds.create.tsx");
  "routes/webhooks.orders.create": typeof import("./app/routes/webhooks.orders.create.tsx");
  "routes/api.download-receipt": typeof import("./app/routes/api.download-receipt.tsx");
  "routes/webhooks.shop.redact": typeof import("./app/routes/webhooks.shop.redact.tsx");
  "routes/api.preview-receipt": typeof import("./app/routes/api.preview-receipt.tsx");
  "routes/api.cron.reminders": typeof import("./app/routes/api.cron.reminders.tsx");
  "routes/api.selling-plans": typeof import("./app/routes/api.selling-plans.ts");
  "routes/api.block-config": typeof import("./app/routes/api.block-config.tsx");
  "routes/api.cron.billing": typeof import("./app/routes/api.cron.billing.tsx");
  "routes/api.portion-sale": typeof import("./app/routes/api.portion-sale.tsx");
  "routes/api.portion-sale.settings": typeof import("./app/routes/api.portion-sale.settings.tsx");
  "routes/api.plan-status": typeof import("./app/routes/api.plan-status.tsx");
  "routes/privacy-policy": typeof import("./app/routes/privacy-policy.tsx");
  "routes/api.campaigns": typeof import("./app/routes/api.campaigns.tsx");
  "routes/documentation": typeof import("./app/routes/documentation.tsx");
  "routes/subscriptions": typeof import("./app/routes/subscriptions.tsx");
  "routes/subscriptions.$id": typeof import("./app/routes/subscriptions.$id.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/receipts": typeof import("./app/routes/receipts.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.recurring-subscriptions_.edit": typeof import("./app/routes/app.recurring-subscriptions_.edit.tsx");
  "routes/app.preset-donation_.delete.$id": typeof import("./app/routes/app.preset-donation_.delete.$id.tsx");
  "routes/app.preset-donation_.edit.$id": typeof import("./app/routes/app.preset-donation_.edit.$id.tsx");
  "routes/app.recurring-subscriptions": typeof import("./app/routes/app.recurring-subscriptions.tsx");
  "routes/app.preset-donation_.add": typeof import("./app/routes/app.preset-donation_.add.tsx");
  "routes/app.subscription-detail": typeof import("./app/routes/app.subscription-detail.tsx");
  "routes/app.donation-activity": typeof import("./app/routes/app.donation-activity.tsx");
  "routes/app.billing-attempts": typeof import("./app/routes/app.billing-attempts.tsx");
  "routes/app.payment-recovery": typeof import("./app/routes/app.payment-recovery.tsx");
  "routes/app.perset-donation": typeof import("./app/routes/app.perset-donation.tsx");
  "routes/app.preset-donation": typeof import("./app/routes/app.preset-donation.tsx");
  "routes/app.email-settings": typeof import("./app/routes/app.email-settings.tsx");
  "routes/app.track-donation": typeof import("./app/routes/app.track-donation.tsx");
  "routes/app.portion-sale": typeof import("./app/routes/app.portion-sale.tsx");
  "routes/app.diagnostics": typeof import("./app/routes/app.diagnostics.tsx");
  "routes/app.billing": typeof import("./app/routes/app.billing.tsx");
  "routes/app.pricing": typeof import("./app/routes/app.pricing.tsx");
  "routes/app.roundup": typeof import("./app/routes/app.roundup.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.help": typeof import("./app/routes/app.help.tsx");
  "routes/faq": typeof import("./app/routes/faq.tsx");
};